In [14]:
import pandas as pd
df = pd.read_csv('data/french-ambs.csv')
df.shape

(869, 7)

In [15]:
df

,id,name,place,year,lat,long,lat_long
0,0,"Richer, Christophe",Denmark,1543,55.68,12.57,"55.68, 12.57"
1,1,"Richer, Christophe",Denmark,1541,55.68,12.57,"55.68, 12.57"
2,2,"Danzay, Charles de",Denmark,1561,55.68,12.57,"55.68, 12.57"
3,3,"Danzay, Charles de",Denmark,1563,55.68,12.57,"55.68, 12.57"
4,4,"Danzay, Charles de",Denmark,1582,55.68,12.57,"55.68, 12.57"
...,...,...,...,...,...,...,...
864,864,"Canossa, Louis de",Venice,1526,45.44,12.33,"45.44, 12.33"
865,865,"Vigier, Jacques",Swiss Cantons,1597,46.94,7.45,"46.94, 7.45"
866,866,"De Selve, Georges",Venice,1537,45.44,12.33,"45.44, 12.33"
867,867,"Noailles, François de, Bishop of Dax",Venice,1559,45.44,12.33,"45.44, 12.33"
868,868,"Calvimont, Jean de",Holy Roman Empire,1525,48.21,16.36,"48.21, 16.36"

In [16]:
df_filter = df[(df['year'] < 1592) & (df['year'] > 1588)]
df_filter.shape

(21, 7)

In [17]:
df["is_permanent"] = True
df

,id,name,place,year,lat,long,lat_long,is_permanent
0,0,"Richer, Christophe",Denmark,1543,55.68,12.57,"55.68, 12.57",True
1,1,"Richer, Christophe",Denmark,1541,55.68,12.57,"55.68, 12.57",True
2,2,"Danzay, Charles de",Denmark,1561,55.68,12.57,"55.68, 12.57",True
3,3,"Danzay, Charles de",Denmark,1563,55.68,12.57,"55.68, 12.57",True
4,4,"Danzay, Charles de",Denmark,1582,55.68,12.57,"55.68, 12.57",True
...,...,...,...,...,...,...,...,...
864,864,"Canossa, Louis de",Venice,1526,45.44,12.33,"45.44, 12.33",True
865,865,"Vigier, Jacques",Swiss Cantons,1597,46.94,7.45,"46.94, 7.45",True
866,866,"De Selve, Georges",Venice,1537,45.44,12.33,"45.44, 12.33",True
867,867,"Noailles, François de, Bishop of Dax",Venice,1559,45.44,12.33,"45.44, 12.33",True
868,868,"Calvimont, Jean de",Holy Roman Empire,1525,48.21,16.36,"48.21, 16.36",True

In [18]:
df["is_permanent"][(df["place"] == "Geneva") | (df["place"] == "Saxony") | (df["place"] == "Tuscany") | (df["place"] == "Ferrara")] = False

/var/folders/cc/k2w3n13x3sndt6mbgq0813c40000gp/T/ipykernel_88368/495637465.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["is_permanent"][(df["place"] == "Geneva") | (df["place"] == "Saxony") | (df["place"] == "Tuscany") | (df["place"] == "Ferrara")] = False
/var/folders/cc/k2w3n13x3sndt6mbgq0813c40000gp/T/ipykernel_88368/495637465.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["is_permanent"][(df["place"] == "Geneva") | (df["place"] == "Saxony") | (df["place"] == "Tuscany") | (df["place"] == "Ferrara")] = False

In [19]:
df[df["is_permanent"] == False].shape

(11, 8)

In [20]:
df["place"][(df["place"] == "Geneva") | (df["place"] == "Grisons")] = "Swiss Cantons"

/var/folders/cc/k2w3n13x3sndt6mbgq0813c40000gp/T/ipykernel_88368/614014330.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["place"][(df["place"] == "Geneva") | (df["place"] == "Grisons")] = "Swiss Cantons"
/var/folders/cc/k2w3n13x3sndt6mbgq0813c40000gp/T/ipykernel_88368/614014330.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["place"][(df["place"] == "Geneva") | (df["place"] == "Grisons")] = "Swiss Cantons"

In [21]:
df

,id,name,place,year,lat,long,lat_long,is_permanent
0,0,"Richer, Christophe",Denmark,1543,55.68,12.57,"55.68, 12.57",True
1,1,"Richer, Christophe",Denmark,1541,55.68,12.57,"55.68, 12.57",True
2,2,"Danzay, Charles de",Denmark,1561,55.68,12.57,"55.68, 12.57",True
3,3,"Danzay, Charles de",Denmark,1563,55.68,12.57,"55.68, 12.57",True
4,4,"Danzay, Charles de",Denmark,1582,55.68,12.57,"55.68, 12.57",True
...,...,...,...,...,...,...,...,...
864,864,"Canossa, Louis de",Venice,1526,45.44,12.33,"45.44, 12.33",True
865,865,"Vigier, Jacques",Swiss Cantons,1597,46.94,7.45,"46.94, 7.45",True
866,866,"De Selve, Georges",Venice,1537,45.44,12.33,"45.44, 12.33",True
867,867,"Noailles, François de, Bishop of Dax",Venice,1559,45.44,12.33,"45.44, 12.33",True
868,868,"Calvimont, Jean de",Holy Roman Empire,1525,48.21,16.36,"48.21, 16.36",True

In [22]:
df[df["place"] == "Swiss Cantons"].shape

(210, 8)

In [23]:
df_agg = df.groupby(["place"]).agg({"year": "nunique", "name": "nunique"})
df_agg

                   year  name
place
Denmark              40     2
England              74    26
Ferrara               3     2
Holy Roman Empire    70    15
Netherlands          43    12
Ottoman Empire       66    20
Poland                3     5
Portugal             55     5
Rome                 59    24
Savoy                 3     3
Saxony                3     1
Scotland             21     4
Spain                31     5
Swiss Cantons        79    39
Tuscany               3     1
Venice               80    20

In [24]:
df_agg = df_agg.rename(columns={"year": "years_present", "name": "unique_ambs"})
df_agg.sort_values(by="unique_ambs", ascending=True)

                   years_present  unique_ambs
place
Saxony                         3            1
Tuscany                        3            1
Denmark                       40            2
Ferrara                        3            2
Savoy                          3            3
Scotland                      21            4
Poland                         3            5
Portugal                      55            5
Spain                         31            5
Netherlands                   43           12
Holy Roman Empire             70           15
Ottoman Empire                66           20
Venice                        80           20
Rome                          59           24
England                       74           26
Swiss Cantons                 79           39

In [27]:
df_agg.sort_values(by='unique_ambs')

                   years_present  unique_ambs
place
Saxony                         3            1
Tuscany                        3            1
Denmark                       40            2
Ferrara                        3            2
Savoy                          3            3
Scotland                      21            4
Poland                         3            5
Portugal                      55            5
Spain                         31            5
Netherlands                   43           12
Holy Roman Empire             70           15
Ottoman Empire                66           20
Venice                        80           20
Rome                          59           24
England                       74           26
Swiss Cantons                 79           39